// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: proto/shotis.proto

package network

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//HealthReportRequest is a request sent by a client to receive a health report
type HealthReportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HealthReportRequest) Reset() {
	*x = HealthReportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shotis_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthReportRequest) ProtoMessage() {}

func (x *HealthReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shotis_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthReportRequest.ProtoReflect.Descriptor instead.
func (*HealthReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_shotis_proto_rawDescGZIP(), []int{0}
}

//HealthReport reports the current health of the service such as
// memory usage, awaiting processes, statistics, and anything else I can think of
type HealthReport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MemoryUsage     float64 `protobuf:"fixed64,1,opt,name=MemoryUsage,proto3" json:"MemoryUsage,omitempty"`
	Allocated       float64 `protobuf:"fixed64,2,opt,name=Allocated,proto3" json:"Allocated,omitempty"`
	Free            float64 `protobuf:"fixed64,3,opt,name=Free,proto3" json:"Free,omitempty"`
	AwaitingWorkers int32   `protobuf:"varint,4,opt,name=AwaitingWorkers,proto3" json:"AwaitingWorkers,omitempty"`
	IdleWorkers     int32   `protobuf:"varint,5,opt,name=IdleWorkers,proto3" json:"IdleWorkers,omitempty"`
	UploadedImages  int32   `protobuf:"varint,6,opt,name=UploadedImages,proto3" json:"UploadedImages,omitempty"`
	Uptime          uint64  `protobuf:"varint,7,opt,name=Uptime,proto3" json:"Uptime,omitempty"`
}

func (x *HealthReport) Reset() {
	*x = HealthReport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shotis_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthReport) ProtoMessage() {}

func (x *HealthReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shotis_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthReport.ProtoReflect.Descriptor instead.
func (*HealthReport) Descriptor() ([]byte, []int) {
	return file_proto_shotis_proto_rawDescGZIP(), []int{1}
}

func (x *HealthReport) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *HealthReport) GetAllocated() float64 {
	if x != nil {
		return x.Allocated
	}
	return 0
}

func (x *HealthReport) GetFree() float64 {
	if x != nil {
		return x.Free
	}
	return 0
}

func (x *HealthReport) GetAwaitingWorkers() int32 {
	if x != nil {
		return x.AwaitingWorkers
	}
	return 0
}

func (x *HealthReport) GetIdleWorkers() int32 {
	if x != nil {
		return x.IdleWorkers
	}
	return 0
}

func (x *HealthReport) GetUploadedImages() int32 {
	if x != nil {
		return x.UploadedImages
	}
	return 0
}

func (x *HealthReport) GetUptime() uint64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

type UploadImageMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName string `protobuf:"bytes,1,opt,name=FileName,proto3" json:"FileName,omitempty"`
	MimeType string `protobuf:"bytes,2,opt,name=MimeType,proto3" json:"MimeType,omitempty"`
	Data     []byte `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *UploadImageMessage) Reset() {
	*x = UploadImageMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shotis_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadImageMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageMessage) ProtoMessage() {}

func (x *UploadImageMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shotis_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageMessage.ProtoReflect.Descriptor instead.
func (*UploadImageMessage) Descriptor() ([]byte, []int) {
	return file_proto_shotis_proto_rawDescGZIP(), []int{2}
}

func (x *UploadImageMessage) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadImageMessage) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *UploadImageMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadImageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageId string `protobuf:"bytes,1,opt,name=ImageId,proto3" json:"ImageId,omitempty"`
	URL     string `protobuf:"bytes,2,opt,name=URL,proto3" json:"URL,omitempty"`
}

func (x *UploadImageResponse) Reset() {
	*x = UploadImageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shotis_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageResponse) ProtoMessage() {}

func (x *UploadImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shotis_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageResponse.ProtoReflect.Descriptor instead.
func (*UploadImageResponse) Descriptor() ([]byte, []int) {
	return file_proto_shotis_proto_rawDescGZIP(), []int{3}
}

func (x *UploadImageResponse) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *UploadImageResponse) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

var File_proto_shotis_proto protoreflect.FileDescriptor

var file_proto_shotis_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x68, 0x6f, 0x74, 0x69, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x68, 0x6f, 0x74, 0x69, 0x73, 0x22, 0x15, 0x0a, 0x13,
	0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0xee, 0x01, 0x0a, 0x0c, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x55, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x4d, 0x65, 0x6d, 0x6f, 0x72,
	0x79, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61,
	0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x41, 0x6c, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x72, 0x65, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x04, 0x46, 0x72, 0x65, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x41, 0x77, 0x61, 0x69,
	0x74, 0x69, 0x6e, 0x67, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0f, 0x41, 0x77, 0x61, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x57, 0x6f, 0x72, 0x6b, 0x65,
	0x72, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x49, 0x64, 0x6c, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72,
	0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x49, 0x64, 0x6c, 0x65, 0x57, 0x6f, 0x72,
	0x6b, 0x65, 0x72, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x55, 0x70, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x55, 0x70,
	0x74, 0x69, 0x6d, 0x65, 0x22, 0x60, 0x0a, 0x12, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x69,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x69,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x69, 0x6d, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4d, 0x69, 0x6d, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x41, 0x0a, 0x13, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x52, 0x4c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x52, 0x4c, 0x32, 0x96, 0x01, 0x0a, 0x0d, 0x53, 0x68,
	0x6f, 0x74, 0x69, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x0b, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x2e, 0x73, 0x68, 0x6f,
	0x74, 0x69, 0x73, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x1b, 0x2e, 0x73, 0x68, 0x6f, 0x74, 0x69, 0x73, 0x2e,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x12,
	0x1b, 0x2e, 0x73, 0x68, 0x6f, 0x74, 0x69, 0x73, 0x2e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x73,
	0x68, 0x6f, 0x74, 0x69, 0x73, 0x2e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2e, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_shotis_proto_rawDescOnce sync.Once
	file_proto_shotis_proto_rawDescData = file_proto_shotis_proto_rawDesc
)

func file_proto_shotis_proto_rawDescGZIP() []byte {
	file_proto_shotis_proto_rawDescOnce.Do(func() {
		file_proto_shotis_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_shotis_proto_rawDescData)
	})
	return file_proto_shotis_proto_rawDescData
}

var file_proto_shotis_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_shotis_proto_goTypes = []interface{}{
	(*HealthReportRequest)(nil), // 0: shotis.HealthReportRequest
	(*HealthReport)(nil),        // 1: shotis.HealthReport
	(*UploadImageMessage)(nil),  // 2: shotis.UploadImageMessage
	(*UploadImageResponse)(nil), // 3: shotis.UploadImageResponse
}
var file_proto_shotis_proto_depIdxs = []int32{
	2, // 0: shotis.ShotisService.UploadImage:input_type -> shotis.UploadImageMessage
	0, // 1: shotis.ShotisService.Health:input_type -> shotis.HealthReportRequest
	3, // 2: shotis.ShotisService.UploadImage:output_type -> shotis.UploadImageResponse
	1, // 3: shotis.ShotisService.Health:output_type -> shotis.HealthReport
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_shotis_proto_init() }
func file_proto_shotis_proto_init() {
	if File_proto_shotis_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_shotis_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthReportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shotis_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthReport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shotis_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadImageMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shotis_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadImageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_shotis_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_shotis_proto_goTypes,
		DependencyIndexes: file_proto_shotis_proto_depIdxs,
		MessageInfos:      file_proto_shotis_proto_msgTypes,
	}.Build()
	File_proto_shotis_proto = out.File
	file_proto_shotis_proto_rawDesc = nil
	file_proto_shotis_proto_goTypes = nil
	file_proto_shotis_proto_depIdxs = nil
}
